name:          template
version:       0.0.0.1
copyright:     2018 Hilco Wijbenga
license:       GPL-3
author:        Hilco Wijbenga
maintainer:    Hilco Wijbenga
category:      Utility

library:
    source-dirs: src/main/eta/
    exposed-modules:
        Hilcode.Template
    dependencies:
        - base
        - containers
        - megaparsec
        - text

extra-source-files:
    - COPYRIGHT
    - LICENSE
    - package.yaml

ghc-options:
    - -Wall
    # - -Wcompat                  // Unsupported by Eta
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    # - -Wredundant-constraints   // Unsupported by Eta

default-extensions:
    - ApplicativeDo
    - BangPatterns
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    # - DeriveLift                // Unsupported by Eta
    - DeriveTraversable
    # - DerivingStrategies        // Unsupported by Eta
    - EmptyCase
    - ExistentialQuantification
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving 
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - OverloadedStrings
    - PartialTypeSignatures
    - PatternSynonyms
    - RankNTypes
    - ScopedTypeVariables
    - StandaloneDeriving
    - TupleSections
    # - TypeApplications          // Unsupported by Eta
    - TypeFamilies
    # - TypeFamilyDependencies    // Unsupported by Eta
    - TypeOperators
