name:                teng
version:             0.0.0.1
github:              hilcode/teng
homepage:            https://github.com/hilcode/teng#readme
copyright:           2022 Hilco Wijbenga
license:             GPL-3
author:              Hilco Wijbenga
maintainer:          Hilco Wijbenga
category:            Utility

extra-source-files:
  - README.md

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoMonomorphismRestriction
  - OverloadedStrings
  - ScopedTypeVariables
  - Strict
  - TupleSections
  - UndecidableInstances

ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wtabs
  - -Wno-name-shadowing

dependencies:
  - base
  - containers
  - hedgehog
  - hedgehog-classes
  - hspec
  - hw-hspec-hedgehog
  - text
  - vector

executables:
    teng:
        source-dirs:
          - src/main/haskell
        main: Main.hs
        dependencies:
          - teng

library:
    source-dirs:
      - src/main/haskell
    exposed-modules:
      - Hilcode.DataType
      - Hilcode.DataType.Internal
      - Hilcode.FieldName
      - Hilcode.FieldName.Internal
      - Hilcode.JsonParser
      - Hilcode.JsonValue
      - Hilcode.JsonValue.Internal
      - Hilcode.Key
      - Hilcode.Misc
      - Hilcode.Parser

tests:
    test:
        source-dirs:
          - src/test/haskell
        main: Spec.hs
        dependencies:
          - base
          - teng
        other-modules:
          - Hilcode.DataType.InternalSpec
          - Hilcode.FieldName.InternalSpec
          - Hilcode.JsonParserSpec
          - Hilcode.MiscSpec
