resolver: ghc-8.4.3

allow-newer: true

packages:
    - ./
    - file-system/
    - show-text/
    - template/

extra-deps:
    - base-compat-0.10.4
    - base-compat-batteries-0.10.4
    - base-orphans-0.8
    - bifunctors-5.5.3
    - bytestring-builder-0.10.8.1.0
    - cabal-doctest-1.0.6
    - case-insensitive-1.2.0.11
    - comonad-5.0.4
    - containers-0.5.11.0
    - contravariant-1.5
    - dequeue-0.1.12
    - directory-1.3.3.1
    - distributive-0.6
    - erf-2.0.0.0
    - generic-deriving-1.12.2
    - hashable-1.2.7.0
    - integer-logarithms-1.0.2.1
    - megaparsec-7.0.0
    - nats-1.1.2
    - parser-combinators-1.0.0
    - primitive-0.6.4.0
    - QuickCheck-2.12
    - random-1.1
    - safe-0.3.17
    - scientific-0.3.6.2
    - semigroups-0.18.5
    - StateVar-1.1.1.1
    - strings-1.1
    - tagged-0.8.6
    - text-1.2.3.0
    - text-show-3.7.4
    - tf-random-0.5
    - th-abstraction-0.2.8.0
    - th-lift-0.7.11
    - transformers-compat-0.6.2
    - void-0.7.2
