resolver: ghc-8.4.3

allow-newer: true

extra-deps:
- aeson-1.4.0.0
- ansi-terminal-0.8.0.4
- ansi-wl-pprint-0.6.8.2
- appar-0.1.4
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.2.1
- attoparsec-0.13.2.2
- auto-update-0.1.4
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- base-compat-0.10.4
- basement-0.0.8
- base-orphans-0.8
- base-prelude-1.3
- bifunctors-5.5.3
- blaze-builder-0.4.1.0
- bsb-http-chunked-0.0.0.3
- butcher-1.3.1.1
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.6
- call-stack-0.1.0
- case-insensitive-1.2.0.11
- cereal-0.5.7.0
- clock-0.7.2
- cmdargs-0.10.20
- colour-2.3.4
- comonad-5.0.4
- conduit-1.3.0.3
- conduit-extra-1.3.0
- connection-0.2.8
- contravariant-1.5
- cookie-0.4.4
- cpphs-1.20.8
- cryptohash-sha256-0.11.101.0
- cryptonite-0.25
- czipwith-1.0.1.0
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- data-tree-print-0.1.0.1
- deque-0.2.1
- distributive-0.6
- dlist-0.8.0.4
- easy-file-0.2.2
- echo-0.1.3
- ed25519-0.0.5.0
- edit-distance-0.2.2.1
- erf-2.0.0.0
- exceptions-0.10.0
- extra-1.6.9
- fast-logger-2.4.11
- file-embed-0.0.11
- fmlist-0.9.2
- foundation-0.0.21
- free-5.1
- generic-deriving-1.12.2
- ghc-exactprint-0.5.6.1
- ghc-paths-0.1.0.9
- Glob-0.9.2
- hackage-security-0.5.3.0
- hashable-1.2.7.0
- haskell-src-exts-1.20.2
- haskell-src-exts-util-0.2.3
- hourglass-0.2.12
- hscolour-1.24.4
- hspec-2.5.6
- hspec-core-2.5.6
- hspec-discover-2.5.6
- hspec-expectations-0.8.2
- http2-1.6.3
- HTTP-4000.3.12
- http-client-0.5.13.1
- http-client-tls-0.3.5.3
- http-conduit-2.3.2
- http-date-0.0.8
- http-types-0.12.1
- HUnit-1.6.0.0
- infer-license-0.2.0
- integer-logarithms-1.0.2.1
- iproute-1.7.5
- js-flot-0.8.3
- js-jquery-3.3.1
- ListLike-4.6
- logict-0.6.0.2
- megaparsec-6.5.0
- memory-0.14.16
- microlens-0.4.9.1
- microlens-th-0.4.2.2
- mime-types-0.1.0.8
- mmap-0.5.9
- monad-control-1.0.2.3
- monad-loops-0.4.3
- monad-memo-0.4.1
- mono-traversable-1.0.9.0
- multistate-0.8.0.0
- neat-interpolation-0.3.2.2
- network-2.6.3.6
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.2.0
- parser-combinators-1.0.0
- path-0.6.1
- path-io-1.4.0
- pem-0.2.4
- polyparse-1.12
- primitive-0.6.4.0
- process-extras-0.7.4
- profunctors-5.3
- psqueues-0.2.7.0
- QuickCheck-2.12
- quickcheck-io-0.2.0
- random-1.1
- refact-0.3.0.2
- resolv-0.1.1.1
- resourcet-1.2.1
- safe-0.3.17
- scientific-0.3.6.2
- semigroupoids-5.3.1
- semigroups-0.18.5
- setenv-0.1.1.3
- simple-sendfile-0.2.27
- smallcheck-1.1.5
- socks-0.5.6
- split-0.2.3.3
- StateVar-1.1.1.1
- storable-record-0.0.4
- storable-tuple-0.0.3.3
- streaming-commons-0.2.1.0
- strict-0.3.2
- syb-0.7
- tagged-0.8.6
- tar-0.5.1.0
- tasty-1.1.0.3
- tasty-hspec-1.1.5
- tasty-quickcheck-0.10
- tasty-smallcheck-0.8.1
- temporary-1.3
- text-metrics-0.3.0
- tf-random-0.5
- th-abstraction-0.2.8.0
- time-locale-compat-0.1.1.5
- tls-1.4.1
- tls-session-manager-0.0.0.2
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
- typed-process-0.2.3.0
- unbounded-delays-0.1.1.0
- uniplate-1.6.12
- unix-compat-0.5.1
- unix-time-0.3.8
- unliftio-core-0.1.2.0
- unordered-containers-0.2.9.0
- unsafe-0.0
- utf8-string-1.0.1.1
- utility-ht-0.0.14
- uuid-types-1.0.3
- vault-0.3.1.2
- vector-0.12.0.1
- vector-algorithms-0.7.0.4
- void-0.7.2
- wai-3.2.1.2
- wai-logger-2.3.2
- warp-3.2.24
- warp-tls-3.2.4.3
- wcwidth-0.0.2
- word8-0.1.3
- x509-1.7.3
- x509-store-1.6.6
- x509-system-1.6.6
- x509-validation-1.6.10
- yaml-0.10.1.1
- zlib-0.6.2